id: baseline
parallel: True 
pretrained: #STM_weights.pth
seed: 42

model:
    name: STM
    args:

        
optimizer:
    name: Adam
    args:
        lr: 0.00001
        # momentum: 0.9
        # nesterov: True 
        # <argument keyword>: <argument value>
        # ... more args
loss:
    name: DiceLoss
    args:
        weight: [1, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
        #<argument keyword>: <argument value>
        # ... more args
metric:
    - name: Accuracy
      args:
          #<argument keyword>: <argument value>
          # ... more args
    # ... more metrics
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 3
        verbose: True

dataset:
    train:
        name: StaticImage
        args:
            root: DAVIS
            imset: 2017/train.txt
        loader:
            name: DataLoader
            args:
                shuffle: True
                batch_size: 1
                num_workers: 1
                prefetch_factor: 1
                
    val:
        name: StaticImage
        args:
            root: DAVIS
            imset: 2017/val.txt
        loader:
            name: DataLoader
            args:
                shuffle: True
                batch_size: 1
                num_workers: 1
                prefetch_factor: 1
trainer:
    nepochs: 100
    val_step: 1
    log_step: 1
    checkpoint_mini_step: 100
    save_dir: runs